export const ROOM_TYPE_CONFIG = {
  MIN_PRICE_PER_NIGHT: 0,
  MAX_PRICE_PER_NIGHT: 9999999,
  MIN_ALLOWED_ADULTS: 1,
  MAX_ALLOWED_ADULTS: 20,
  MIN_ALLOWED_CHILD: 0,
  MAX_ALLOWED_CHILD: 20,
};

export const HOTEL_CONFIG = {
  MIN_REVIEW_SCORE: 0,
  MAX_REVIEW_SCORE: 10,
};
